algo = input('Digite Algo: ')
print('Qual o tipo primitivo ?', type(algo))
print('É Alfabetico ?', algo.isalpha())
print('É Numerico ?', algo.isnumeric())
print('É Decimal ?', algo.isdecimal())
print('É Maiusculo ?', algo.isupper())
print('É Minusculo ?', algo.islower())
print('É Alfanumerico ?', algo.isalnum())
